<?php namespace KekecMed\Calendar\Http\Controllers;

use Illuminate\Database\Eloquent\Model;
use Illuminate\View\View;
use KekecMed\Calendar\Entities\Calendar;
use KekecMed\Core\Http\Controllers\CoreConventionalResourceViewController;

class CalendarController extends CoreConventionalResourceViewController
{

    public function index()
    {
        return view('calendar::index');
    }

    /**
     * Get Module identifier
     *
     * @return string
     */
    protected function getIdentifier()
    {
        return 'calendar';
    }

    /**
     * Get model class
     *
     * @return Model::class
     */
    protected function getModelClass()
    {
        return Calendar::class;
    }

    /**
     * Show / Hide edit button
     *
     * @return boolean
     */
    public function showEditButton()
    {
        // TODO: Implement showEditButton() method.
    }

    /**
     * Get Validation rules
     *
     * @return array
     */
    public function getValidationRules()
    {
        // TODO: Implement validation rules

        return [];
    }

    /**
     * Executed before index
     *
     * @return mixed
     */
    protected function beforeIndex()
    {
        // TODO: Implement beforeIndex() method.
    }

    /**
     * Execute before store()
     *
     * @param array $data
     *
     * @return mixed
     */
    protected function beforeStore(array $data)
    {
        // TODO: Implement beforeStore() method.
    }

    /**
     * Execute after store()
     *
     * @param Model $model
     *
     * @return mixed
     */
    protected function afterStore(Model $model)
    {
        // TODO: Implement afterStore() method.
    }

    /**
     * Before update()
     *
     * @param $id
     * @param $data
     *
     * @return mixed
     */
    protected function beforeUpdate($id, $data)
    {
        // TODO: Implement beforeUpdate() method.
    }

    protected function beforeCreate(Model $model, View $view)
    {
        // TODO: Change the autogenerated stub
    }
}